### ISSUE TITLE
Starts are still buttons in readOnly

### ISSUE THREAD

**Issue by goferito** [TeamWertarbyte/material-ui-rating#6]
Then, if the style is changed to have the stars smaller and closer to each other (because they don't need to be clicked, and look better in the design), google's test will consider that those button elements are too close, and the page is not mobile friendly.

**Comment by saschb2b** [comment]
Can you please post the related sources and test passing requirements ?

**Comment by goferito** [comment]
I'm sorry, but I don't understand the question

**Comment by saschb2b** [comment]
You say that google checks for mobile friendly. What are the needed changes in order to make this component mobile friendly? Like a UI guideline in some sort.
At the moment they do have 12px padding. Is that too much? If so what value is correct is they are readOnly to make it mobile friendly.
The only guideline I see is from https://material.io/guidelines/components/cards.html#cards-actions
Showing two images without a specific padding.

![](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3OXdMTGNiaG9MVXc/components_cards_action1.png)

![](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3UWdmRm15cGR2TGM/components_cards_action4.png)

We need a specific guideline or a test to see whats mobile friendly and whats not. How did you test it?

**Comment by saschb2b** [comment]
@goferito any ideas on how we should tackle this? I tested googles test for mobile friendly and it passed.
![image](https://cloud.githubusercontent.com/assets/2778161/26342768/9beb6092-3f99-11e7-9846-610cf0df61e1.png)

**Comment by saschb2b** [comment]
We can try removing the paddng completely and setting width and height to 24px isntead of 48px. Resulting in this
![image](https://cloud.githubusercontent.com/assets/2778161/26342949/618d3492-3f9a-11e7-9cac-f852f25797a4.png)

**Comment by saschb2b** [comment]
Closed due to no answer
